# Generated by Django 5.2.1 on 2025-06-19 12:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PumpTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('ofankor', 'Ofankor'), ('palmwine', 'Palmwine'), ('eastlegon', 'East Legon'), ('achimota_ksi', 'Achimota KSI'), ('achimota_abofu', 'Achimota Abofu'), ('bohye', 'Bohye'), ('airport', 'Airport')], max_length=15)),
                ('pump', models.CharField(choices=[('pump1', 'Pump 1'), ('pump2', 'Pump 2'), ('pump3', 'Pump 3'), ('pump4', 'Pump 4'), ('pump5', 'Pump 5')], max_length=10)),
                ('target', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_noRole', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('ofankor', 'Ofankor'), ('palmwine', 'Palmwine'), ('eastlegon', 'East Legon'), ('achimota_ksi', 'Achimota KSI'), ('achimota_abofu', 'Achimota Abofu'), ('bohye', 'Bohye'), ('airport', 'Airport')], max_length=15)),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('car_number', models.CharField(max_length=20)),
                ('litres', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sales', to='employee.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_collections', to='employee.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('contact', models.CharField(max_length=20)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('location', models.CharField(max_length=200)),
                ('guarantor_name', models.CharField(max_length=100)),
                ('guarantor_contact', models.CharField(max_length=20)),
                ('job_description', models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('quality_marshal', 'Quality Marshal'), ('customer_champion', 'Customer Champion'), ('service_champion', 'Service Champion'), ('lube_technician', 'Lube Technician'), ('oil_specialist', 'Oil Specialist'), ('cleaner', 'Cleaner'), ('security', 'Security'), ('driver', 'Driver')], max_length=50)),
                ('date_employed', models.DateField()),
                ('training_start', models.DateField()),
                ('training_end', models.DateField()),
                ('ssnit', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('account', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('site', models.CharField(choices=[('ofankor', 'Ofankor'), ('palmwine', 'Palmwine'), ('eastlegon', 'East Legon'), ('achimota_ksi', 'Achimota KSI'), ('achimota_abofu', 'Achimota Abofu'), ('bohye', 'Bohye'), ('airport', 'Airport')], max_length=15)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField()),
                ('percentage_mark', models.FloatField(blank=True, null=True)),
                ('attendance_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_mark', to='employee.attendancedate')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FuelSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pump', models.CharField(choices=[('pump1', 'Pump 1'), ('pump2', 'Pump 2'), ('pump3', 'Pump 3'), ('pump4', 'Pump 4'), ('pump5', 'Pump 5')], max_length=10)),
                ('pms_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dx_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vp_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('performance', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sales', to='employee.captain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_sales', to='employee.captain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendantEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.FloatField()),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('weekly_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_scores', to='employee.weeklyevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('off', 'Off Day')], default='present', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
