# Generated by Django 5.2.1 on 2025-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='fuelsales',
            unique_together={('user', 'date')},
        ),
    ]
