# Generated by Django 5.2.1 on 2025-06-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_fuelsales_date_alter_fuelsales_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('ofankor', 'Ofankor'), ('palmwine', 'Palmwine'), ('eastlegon', 'East Legon'), ('achimota_ksi', 'Achimota KSI'), ('achimota_abofu', 'Achimota Abofu'), ('bohye', 'Bohye'), ('airport', 'Airport')], max_length=15)),
                ('target', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fuelsales',
            unique_together=set(),
        ),
    ]
