# Generated by Django 5.2.1 on 2025-06-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_shoptarget_alter_fuelsales_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsales',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
