# Generated by Django 5.2.1 on 2025-06-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_shopsales_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='shopsales',
            unique_together={('user', 'date')},
        ),
    ]
